"use client";
import React from "react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell
} from "recharts";
import { TrendingUp, PieChart as PieIcon } from "lucide-react";


const growthData = [
  { month: "Jan", Users: 1200, Bookings: 800 },
  { month: "Feb", Users: 1900, Bookings: 1200 },
  { month: "Mar", Users: 3200, Bookings: 2100 },
  { month: "Apr", Users: 4100, Bookings: 2900 },
  { month: "May", Users: 5600, Bookings: 4300 },
  { month: "Jun", Users: 7000, Bookings: 5800 },
];


const serviceData = [
  { name: "Consultations", value: 400 },
  { name: "Reservations", value: 300 },
  { name: "Support Tickets", value: 200 },
  { name: "Other Services", value: 100 },
];


const COLORS = ["#6366f1", "#10b981", "#f59e0b", "#ef4444"];

export default function ChartsPage() {
  return (
    <div className="space-y-8">
      {/* هيدر الصفحة */}
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-50 tracking-tight flex items-center gap-2">
          <TrendingUp className="h-6 w-6 text-indigo-600 dark:text-indigo-400" />
          Advanced Analytics & Growth Charts
        </h1>
        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
          Monitor your platform user growth curves and service distribution proportions.
        </p>
      </div>

     
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        
        <div className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
          <div className="mb-4">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 flex items-center gap-2">
              Growth Analytics (Line)
            </h2>
            <p className="text-xs text-slate-400 dark:text-slate-500">Active users vs completed reservations over time.</p>
          </div>

          <div className="h-[320px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={growthData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-slate-200 dark:stroke-slate-800" />
                <XAxis dataKey="month" className="text-xs text-slate-400 dark:text-slate-500" tickLine={false} />
                <YAxis className="text-xs text-slate-400 dark:text-slate-500" tickLine={false} axisLine={false} />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "var(--tooltip-bg, #ffffff)",
                    borderColor: "var(--tooltip-border, #e2e8f0)",
                    borderRadius: "12px",
                  }}
                  className="dark:[--tooltip-bg:#1e293b] dark:[--tooltip-border:#334155]"
                />
                <Legend wrapperStyle={{ paddingTop: "15px", fontSize: "13px" }} />
               
                <Line type="monotone" dataKey="Users" stroke="#4f46e5" strokeWidth={3} dot={{ r: 4 }} activeDot={{ r: 6 }} />
               
                <Line type="monotone" dataKey="Bookings" stroke="#10b981" strokeWidth={3} dot={{ r: 4 }} activeDot={{ r: 6 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        
        <div className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
          <div className="mb-4">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 flex items-center gap-2">
              <PieIcon className="h-5 w-5 text-indigo-500" />
              Service Distribution (Pie)
            </h2>
            <p className="text-xs text-slate-400 dark:text-slate-500">Proportion of business generated by each category.</p>
          </div>

          <div className="h-[320px] w-full flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={serviceData}
                  cx="50%"
                  cy="45%"
                  innerRadius={60} 
                  outerRadius={90}
                  paddingAngle={5}
                  dataKey="value"
                >
                  
                  {serviceData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip
                  contentStyle={{
                    backgroundColor: "var(--tooltip-bg, #ffffff)",
                    borderColor: "var(--tooltip-border, #e2e8f0)",
                    borderRadius: "12px",
                  }}
                  className="dark:[--tooltip-bg:#1e293b] dark:[--tooltip-border:#334155]"
                />
                <Legend verticalAlign="bottom" height={36} wrapperStyle={{ fontSize: "13px" }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

      </div>
    </div>
  );
}